<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1kfxluT\srcApp_KernelEnvDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1kfxluT/srcApp_KernelEnvDebugContainer.php') {
    touch(__DIR__.'/Container1kfxluT.legacy');

    return;
}

if (!\class_exists(srcApp_KernelEnvDebugContainer::class, false)) {
    \class_alias(\Container1kfxluT\srcApp_KernelEnvDebugContainer::class, srcApp_KernelEnvDebugContainer::class, false);
}

return new \Container1kfxluT\srcApp_KernelEnvDebugContainer([
    'container.build_hash' => '1kfxluT',
    'container.build_id' => 'b112aea1',
    'container.build_time' => 1590248609,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1kfxluT');
