<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGMshC2S\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGMshC2S/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerGMshC2S.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerGMshC2S\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerGMshC2S\srcApp_KernelProdContainer([
    'container.build_hash' => 'GMshC2S',
    'container.build_id' => 'ff22fb91',
    'container.build_time' => 1592551072,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGMshC2S');
