<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Produit extends \App\Entity\Produit implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'Nom', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'Prix', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'Date_Limite', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'Taux_Sucre', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'Taux_Sel', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'Taux_Proteine', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'Taux_Fibre', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'Taux_Energie', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'Taux_Gras', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'Taux_Additif', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'compoRecettes', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'historiqueAchats', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'marque', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'taux_calcium', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'taux_sodium', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'nutriscore_grade'];
        }

        return ['__isInitialized__', 'id', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'Nom', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'Prix', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'Date_Limite', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'Taux_Sucre', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'Taux_Sel', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'Taux_Proteine', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'Taux_Fibre', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'Taux_Energie', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'Taux_Gras', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'Taux_Additif', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'compoRecettes', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'historiqueAchats', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'marque', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'taux_calcium', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'taux_sodium', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'nutriscore_grade'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Produit $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getNom(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom(string $Nom): \App\Entity\Produit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$Nom]);

        return parent::setNom($Nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrix(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrix', []);

        return parent::getPrix();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrix(string $Prix): \App\Entity\Produit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrix', [$Prix]);

        return parent::setPrix($Prix);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateLimite(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateLimite', []);

        return parent::getDateLimite();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateLimite(\DateTimeInterface $Date_Limite): \App\Entity\Produit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateLimite', [$Date_Limite]);

        return parent::setDateLimite($Date_Limite);
    }

    /**
     * {@inheritDoc}
     */
    public function getTauxSucre(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTauxSucre', []);

        return parent::getTauxSucre();
    }

    /**
     * {@inheritDoc}
     */
    public function setTauxSucre(?string $Taux_Sucre): \App\Entity\Produit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTauxSucre', [$Taux_Sucre]);

        return parent::setTauxSucre($Taux_Sucre);
    }

    /**
     * {@inheritDoc}
     */
    public function getTauxSel(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTauxSel', []);

        return parent::getTauxSel();
    }

    /**
     * {@inheritDoc}
     */
    public function setTauxSel(?string $Taux_Sel): \App\Entity\Produit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTauxSel', [$Taux_Sel]);

        return parent::setTauxSel($Taux_Sel);
    }

    /**
     * {@inheritDoc}
     */
    public function getTauxProteine(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTauxProteine', []);

        return parent::getTauxProteine();
    }

    /**
     * {@inheritDoc}
     */
    public function setTauxProteine(?string $Taux_Proteine): \App\Entity\Produit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTauxProteine', [$Taux_Proteine]);

        return parent::setTauxProteine($Taux_Proteine);
    }

    /**
     * {@inheritDoc}
     */
    public function getTauxFibre(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTauxFibre', []);

        return parent::getTauxFibre();
    }

    /**
     * {@inheritDoc}
     */
    public function setTauxFibre(?string $Taux_Fibre): \App\Entity\Produit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTauxFibre', [$Taux_Fibre]);

        return parent::setTauxFibre($Taux_Fibre);
    }

    /**
     * {@inheritDoc}
     */
    public function getTauxEnergie(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTauxEnergie', []);

        return parent::getTauxEnergie();
    }

    /**
     * {@inheritDoc}
     */
    public function setTauxEnergie(?string $Taux_Energie): \App\Entity\Produit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTauxEnergie', [$Taux_Energie]);

        return parent::setTauxEnergie($Taux_Energie);
    }

    /**
     * {@inheritDoc}
     */
    public function getTauxGras(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTauxGras', []);

        return parent::getTauxGras();
    }

    /**
     * {@inheritDoc}
     */
    public function setTauxGras(?string $Taux_Gras): \App\Entity\Produit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTauxGras', [$Taux_Gras]);

        return parent::setTauxGras($Taux_Gras);
    }

    /**
     * {@inheritDoc}
     */
    public function getNutriscore(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNutriscore', []);

        return parent::getNutriscore();
    }

    /**
     * {@inheritDoc}
     */
    public function setNutriscore(?string $Nutriscore): \App\Entity\Produit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNutriscore', [$Nutriscore]);

        return parent::setNutriscore($Nutriscore);
    }

    /**
     * {@inheritDoc}
     */
    public function getTauxAdditif(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTauxAdditif', []);

        return parent::getTauxAdditif();
    }

    /**
     * {@inheritDoc}
     */
    public function setTauxAdditif(?string $Taux_Additif): \App\Entity\Produit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTauxAdditif', [$Taux_Additif]);

        return parent::setTauxAdditif($Taux_Additif);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompoRecettes(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompoRecettes', []);

        return parent::getCompoRecettes();
    }

    /**
     * {@inheritDoc}
     */
    public function addCompoRecette(\App\Entity\CompoRecette $compoRecette): \App\Entity\Produit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCompoRecette', [$compoRecette]);

        return parent::addCompoRecette($compoRecette);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCompoRecette(\App\Entity\CompoRecette $compoRecette): \App\Entity\Produit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCompoRecette', [$compoRecette]);

        return parent::removeCompoRecette($compoRecette);
    }

    /**
     * {@inheritDoc}
     */
    public function getHistoriqueAchats(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHistoriqueAchats', []);

        return parent::getHistoriqueAchats();
    }

    /**
     * {@inheritDoc}
     */
    public function addHistoriqueAchat(\App\Entity\HistoriqueAchat $historiqueAchat): \App\Entity\Produit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addHistoriqueAchat', [$historiqueAchat]);

        return parent::addHistoriqueAchat($historiqueAchat);
    }

    /**
     * {@inheritDoc}
     */
    public function removeHistoriqueAchat(\App\Entity\HistoriqueAchat $historiqueAchat): \App\Entity\Produit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeHistoriqueAchat', [$historiqueAchat]);

        return parent::removeHistoriqueAchat($historiqueAchat);
    }

    /**
     * {@inheritDoc}
     */
    public function getMarque(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMarque', []);

        return parent::getMarque();
    }

    /**
     * {@inheritDoc}
     */
    public function setMarque(?string $marque): \App\Entity\Produit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMarque', [$marque]);

        return parent::setMarque($marque);
    }

    /**
     * {@inheritDoc}
     */
    public function getTauxCalcium(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTauxCalcium', []);

        return parent::getTauxCalcium();
    }

    /**
     * {@inheritDoc}
     */
    public function setTauxCalcium(?string $taux_calcium): \App\Entity\Produit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTauxCalcium', [$taux_calcium]);

        return parent::setTauxCalcium($taux_calcium);
    }

    /**
     * {@inheritDoc}
     */
    public function getTauxSodium(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTauxSodium', []);

        return parent::getTauxSodium();
    }

    /**
     * {@inheritDoc}
     */
    public function setTauxSodium(?string $taux_sodium): \App\Entity\Produit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTauxSodium', [$taux_sodium]);

        return parent::setTauxSodium($taux_sodium);
    }

    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNutriscoreGrade(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNutriscoreGrade', []);

        return parent::getNutriscoreGrade();
    }

    /**
     * {@inheritDoc}
     */
    public function setNutriscoreGrade(?string $nutriscore_grade): \App\Entity\Produit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNutriscoreGrade', [$nutriscore_grade]);

        return parent::setNutriscoreGrade($nutriscore_grade);
    }

}
