<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6qDWjdY\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6qDWjdY/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6qDWjdY.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6qDWjdY\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container6qDWjdY\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '6qDWjdY',
    'container.build_id' => '1be77f2f',
    'container.build_time' => 1592551477,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6qDWjdY');
